### ISSUE TITLE
[ Landing Page - Automatization ] Automatic open the browser

### ISSUE THREAD

**Issue by Just-Simon-Dev** [Just-Simon-Dev/SchoolProject#3]
napisanie skryptu, który na podstawie godzin (po wygaśnięciu sesji) automatycznie włącza ponownie przeglądarkę z adresem do formularza

**Comment by TheLolik23** [comment]
import webbrowser as web
from datetime import  datetime

dateTime = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
print(dateTime)


#web.open('https://google.com/')
